# (c) Srevin Saju 2020. All rights reserved 
# Licensed under MIT License
# Continuous Integration to release configured AppImages for Element (Riot) desktop client

name: Continuous

on:
  schedule:
    - cron: "5 */12 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: ['stable', 'develop']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build Element
        run: |
          export BUILD_TYPE="${{ matrix.build_type }}"
          bash -ex ./scripts/centos/7/appimage/02*.sh

      - name: Upload Appimage
        uses: actions/upload-artifact@v1
        with:
          name: element-${{ matrix.build_type }}
          path: '_dist'

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: download actions
        uses: actions/download-artifact@v2

      - name: Show releases
        run: ls -alHR
      
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTINUOUS_RELEASE_TAG: ${{ matrix.build_type }}
        run: |
          if [[ "${{ matrix.build_type }}" == "develop" ]]; then
            export GITHUB_CONTINUOUS_RELEASE_TYPE=prerelease
          else
            export GITHUB_CONTINUOUS_RELEASE_TYPE=stable
          fi
          wget https://github.com/srevinsaju/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
          chmod +x pyuploadtool-x86_64.AppImage
          ./pyuploadtool-x86_64.AppImage element-*/*
