# (c) Srevin Saju 2020. All rights reserved 
# Licensed under MIT License
# Continuous Integration to release configured AppImages for Element (Riot) desktop client

name: Continuous

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "5 */12 * * *"

jobs:
  build:
    strategy:
      matrix:
        build_type: ["stable", "develop"]
        node_version: "18"
    name: Build AppImage
    runs-on: ubuntu-20.04
    environment:
      BUILD_TYPE: "${{ matrix.build_type }}"
      NODE_VERSION: "${{ matrix.node_version }}"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "${{ matrix.node_version }"

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build Element
        run: |
          export BUILD_TYPE="${{ matrix.build_type }}"
          bash -ex ./scripts/centos/7/appimage/02*.sh

      - name: Upload Appimage
        uses: actions/upload-artifact@v1
        with:
          name: element-${{ matrix.build_type }}
          path: "_dist"

  release:
    name: Create release and upload artifacts
    needs:
      - build
    runs-on: ubuntu-20.04
    steps:
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTINUOUS_RELEASE_TAG: ${{ matrix.build_type }}
          CHANGELOG_TYPE: conventional
        run: |
          if [[ "${{ matrix.build_type }}" == "develop" ]]; then
            export GITHUB_CONTINUOUS_RELEASE_TAG=continuous
            export GITHUB_CONTINUOUS_RELEASE_TYPE=prerelease
            export GITHUB_CONTINUOUS_RELEASE_NAME="Continuous build"
          else
            export GITHUB_CONTINUOUS_RELEASE_NAME="Stable build"
            export GITHUB_CONTINUOUS_RELEASE_TAG=stable
            export GITHUB_CONTINUOUS_RELEASE_TYPE=stable
          fi
          wget https://github.com/srevinsaju/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
          chmod +x pyuploadtool-x86_64.AppImage
          APPIMAGE_EXTRACT_AND_RUN=1 ./pyuploadtool-x86_64.AppImage _dist/*.AppImage*
