# (c) Srevin Saju 2020. All rights reserved 
# Licensed under MIT License
# Continuous Integration to release configured AppImages for Element (Riot) desktop client

name: Stable

on:
  schedule:
    - cron: "5 */12 * * *"
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  centos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install SqlCipher
        run: |
          bash -ex ./scripts/centos/7/appimage/02*.sh

      - name: Upload Appimage
        uses: actions/upload-artifact@v1
        with:
          name: element-stable
          path: '_dist'



  Release:
    needs: [centos]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [3.8]

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: element-stable


    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/master'
      with:
        automatic_release_tag: stable
        title: Stable AppImage Release
        prerelease: false
        files: |
          element-stable

        repo_token: ${{ secrets.GITHUB_TOKEN }}
 
